name: Run-15-Minutes
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [dev, stg]
    concurrency:
      group: wp-cron-${{ matrix.target }}
      cancel-in-progress: false
    env:
      WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
      GHA_RUN_NO: ${{ github.run_number }}
      GHA_RUN_ID: ${{ github.run_id }}
      GHA_REPO: ${{ github.repository }}
      WPE_ENV: ${{ secrets.WPE_ENV }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Script (${{ matrix.target }})
      run: |
        chmod +x script.sh
        ./script.sh
